/**
 * API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PlayerDto } from './player-dto';


export interface ServerPopulationDto { 
    online?: number;
    max?: number;
    players?: Array<PlayerDto>;
}

